begin;
select plan(14);

-- Arrange: one clinic, one veterinarian. These assertions exercise the triggers and the
-- grants, not RLS, so no access session is needed.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at
)
values
  ('00000000-0000-0000-0000-000000000000', 'a3a3a3a3-0000-0000-0000-0000000000a3',
   'authenticated', 'authenticated', 'ana.columns@example.test', 'not-a-real-hash',
   timezone('utc', now()), '{}'::jsonb, '{}'::jsonb, timezone('utc', now()), timezone('utc', now()));

insert into public.clinics (id, name)
values ('c3c3c3c3-0000-0000-0000-0000000000c3', 'Clínica de prueba de columnas');

insert into public.veterinarians (id, clinic_id, identifier, display_name)
values ('a3a3a3a3-0000-0000-0000-0000000000a3', 'c3c3c3c3-0000-0000-0000-0000000000c3',
        'ana.columns@example.test', 'Ana Columnas');

select set_config('request.jwt.claim.sub', 'a3a3a3a3-0000-0000-0000-0000000000a3', true);

-- ---------------------------------------------------------------------------
-- data-model: created_at is generated by the server, even if the payload sends one.
-- ---------------------------------------------------------------------------

insert into public.clinical_records (id, clinic_id, record_type, content, status, created_at)
values ('d3d3d3d3-0000-0000-0000-0000000000d1', 'c3c3c3c3-0000-0000-0000-0000000000c3',
        'patient', '{"name":"Luna"}', 'draft', '2001-01-01T00:00:00Z');

select ok(
  (select created_at > timezone('utc', now()) - interval '1 minute'
   from public.clinical_records where id = 'd3d3d3d3-0000-0000-0000-0000000000d1'),
  'a client-supplied created_at is replaced by the server clock'
);

-- ---------------------------------------------------------------------------
-- D3: status only changes through approve_clinical_record.
-- ---------------------------------------------------------------------------

insert into public.clinical_records (id, clinic_id, record_type, content, status)
values ('d3d3d3d3-0000-0000-0000-0000000000d2', 'c3c3c3c3-0000-0000-0000-0000000000c3',
        'epicrisis', '{"summary":"borrador"}', 'draft');

select throws_ok(
  $$update public.clinical_records set status = 'approved'
    where id = 'd3d3d3d3-0000-0000-0000-0000000000d2'$$,
  '23514',
  'ATTRIBUTION_IMMUTABLE',
  'an epicrisis cannot be marked approved by a plain UPDATE'
);

select throws_ok(
  $$update public.clinical_records set status = 'corrective'
    where id = 'd3d3d3d3-0000-0000-0000-0000000000d1'$$,
  '23514',
  'ATTRIBUTION_IMMUTABLE',
  'a record cannot become corrective after the fact'
);

-- ---------------------------------------------------------------------------
-- Column grants: the Data API role writes domain columns only.
-- ---------------------------------------------------------------------------

select ok(
  not has_column_privilege('authenticated', 'public.clinical_records', 'approved_by', 'UPDATE'),
  'authenticated cannot update approved_by'
);
select ok(
  not has_column_privilege('authenticated', 'public.clinical_records', 'status', 'UPDATE'),
  'authenticated cannot update status'
);
select ok(
  not has_column_privilege('authenticated', 'public.clinical_records', 'created_at', 'INSERT'),
  'authenticated cannot insert created_at'
);
select ok(
  has_column_privilege('authenticated', 'public.clinical_records', 'content', 'UPDATE'),
  'authenticated can still update the clinical content'
);

-- ---------------------------------------------------------------------------
-- Review #4 follow-up: TRUNCATE bypasses RLS and fires no row triggers, so it must be
-- revoked wherever the Data API role can reach it, alongside the unneeded DELETE.
-- ---------------------------------------------------------------------------

select ok(
  not has_table_privilege('authenticated', 'public.clinical_records', 'TRUNCATE'),
  'authenticated cannot truncate clinical_records'
);
select ok(
  not has_table_privilege('authenticated', 'public.clinical_records', 'DELETE'),
  'authenticated cannot delete clinical_records'
);
select ok(
  not has_table_privilege('authenticated', 'public.clinical_audit_events', 'TRUNCATE'),
  'authenticated cannot truncate clinical_audit_events'
);
select ok(
  not has_table_privilege('authenticated', 'public.clinical_audit_events', 'DELETE'),
  'authenticated cannot delete clinical_audit_events'
);
select ok(
  not has_table_privilege('anon', 'public.clinical_records', 'INSERT'),
  'anon cannot insert clinical_records'
);
select ok(
  not has_table_privilege('anon', 'public.clinical_records', 'UPDATE'),
  'anon cannot update clinical_records'
);

-- ---------------------------------------------------------------------------
-- D4: an update always has an authenticated veterinarian as its actor.
-- ---------------------------------------------------------------------------

select set_config('request.jwt.claim.sub', '', true);
select throws_ok(
  $$update public.clinical_records set content = '{"name":"Luna","weightKg":12}'
    where id = 'd3d3d3d3-0000-0000-0000-0000000000d1'$$,
  '42501',
  'AUTHENTICATION_REQUIRED',
  'an update without an authenticated veterinarian (service role) is rejected'
);

select * from finish();
rollback;
